# exclude rubocop for last lessons not linted
inherit_from: .rubocop_lesson6.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - './*/run.rb'
    - './*/test.rb'
    - './*.rb'
    - './st'
    - 'unused/*/*.rb'

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false


# needs for stprage implementation
Style/ClassVars:
  Exclude:
    - 'lesson7/storage.rb'
    - 'lesson7/station.rb'
    - 'lesson7/modules/instance_counter.rb'

# no need in initializer for this class
Lint/MissingSuper:
  Exclude:
    - 'lesson7/menu.rb'

# return is ok there
Style/RedundantReturn:
  Exclude:
    - 'lesson7/menu.rb'

Metrics/ClassLength:
  Exclude:
    - 'lesson7/menu.rb'
      # - '*/modules/help.rb'

# Offense count: 8
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'lesson7/menu/helper.rb'

Metrics/MethodLength:
  Include:
    - 'lesson7/menu.rb'
  Max: 22

Layout/LineLength:
  Exclude:
    - 'lesson7/menu.rb'
    - 'lesson7/menu/messages.rb'
      # Max: 289

Metrics/AbcSize:
  Include:
    - 'lesson7/menu.rb'
  Max: 28

Metrics/BlockLength:
  Include:
    - 'lesson7/menu.rb'
  Max: 70
