inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - './lesson3/run.rb'
    - './lesson4/run.rb'
    - './lesson4/test.rb'

Style/AsciiComments:
  Enabled: false
