inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - './*/run.rb'
    - './*/test.rb'
    - './*.rb'
    - './st'

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false


# needs for stprage implementation
Style/ClassVars:
  Exclude:
    - '*/storage.rb'
    - '*/station.rb'
    - '*/modules/instance_counter.rb'

# no need in initializer for this class
Lint/MissingSuper:
  Exclude:
    - '*/menu.rb'

# return is ok there
Style/RedundantReturn:
  Exclude:
    - '*/menu.rb'
