language: ruby
cache: bundler
rvm:
- 2.6
- 2.7
before_install: gem update --remote bundler
install:
- bundle install
script:
- bundle exec rubocop
notifications:
  slack:
    secure: o7MdJcPueAoWXBR9oZmB53BQ93v79zf2pSu3UkV7cmbfj7WXWjJ6obx5yQklmmvf2Ol3mEjmq4HktfLS3ShMRMelXx/fVnodKMpHUTGn9u2YZRqXsehx2QPdUPVkNKwLfyblEIFlpscbWoCczmrSJhVkRxdLqaVZ0X+9NlmlElro2kF27RqAxnL+8mun8OeScyMCV+5cXCOlu4ztY3RRos8yyxGuGvhLTVxioMbj8wML6KoxskIFd7zgvHLi0LO6Ng+L8r4mXGQZGB+mNBii3DYgu36GyswsiZkE9mhKbmklkzOHhAbRcawCAhGjtBDO+UuP202cPgbSVHlKY5pRpYMCmptcTJlzD1RL++dvO/ISAOSx0hw3Sexb7mT6HJGE0P7+weAVUd7KESnjTLlQgT1XCjL0+bgcQfjWMEpDIMMw2gPbiMjC9B06jHqsE9vcsyOOh7jZ77I63a5hGb5U2iiGJmhYnKZGJRGh194uPSFJCId7v/Us0UBIq/nMHrve4dBYdSyYp6ksyMjBYdHtifIjsQG5lliyNvhle5rAf0+oikNSn2P6Nrye+odogy1CmIdOec6q+S/q80OIacpZQkdPNeUgWDKznDtQRJztYv5nqBzrwz5ddamAsk3n3kI4s7cIU+OkDMqZeLfnql9C21yeZ4HEamKCTqsv3Aq5v9s=
