language: ruby
cache: bundler
rvm:
- 2.6
- 2.7
before_install: gem update --remote bundler
install:
- bundle install
script:
- bundle exec rubocop
notifications:
  slack:
    secure: nO1LSJukC46LNLLk8U6oQKDRLHOabhGWUgF1rlaSXFQbY4E+Ce1d64b9kWszuynK9ag1C/TaXpesawwpvYlBJaFJIbTuwkIXzlTiBpJvNb2PHmoGUIAsxAH/ADomiFtrhMG4FAOGtV6oiY2Y953o7ET4L9qkbY5cTceha1Cj6N6wa/Uz9HEIK8papJeNNQBWwCGjCdOCy3BOK+VCZzJt4xTOqKAGwfmaC1ClHK3j4k5t99cQUB11tQ0UfUigKdMdy8ZnUJoehTCAgl5FybhtIqQiC/8hoL/BKGv+wXVv4Ho1Uc0i7/VIp0EuPqabC3pQ0NjSD7yI3Sce390EVAi/Qw27QSGQKSbs1PiDkwJrjd0UXjloHpUCdF+0kaTOAvRb3iud19tmj1UHoO+A9ZnhRBlXZHk1AOrC+iXPiu8gRlA5qv/lzBTrALnFRPVNdoXPG+4kO7Yq/re+VeNG2LTD1ImclUAOCYhkmpaaRFyxPj5XEjgMSzU6xSOtZ4L6hp9JW9eWPfV48ajZbgMq1mcWT551tcPsNQgrofpKptF/qyhx4Z8/xeuWnr43mW7h+rhlqwAB5QjzYgVpjku3uFROFNO/o2Fo20JJ7Yi7d606OX5cfedSThocIJH5ppLI4RLBY/LdGDdJZXBisMgSWLjh5hBw49pIA/Lvl16goBaV/JA=
